# Generated by Django 6.1 on 2026-08-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativePOI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('poi_type', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('services_offered', models.TextField(blank=True, help_text='Démarches prises en charge')),
                ('wait_time_minutes', models.IntegerField(default=0, help_text="Temps d'attente estimé")),
            ],
        ),
    ]
